export type KnowledgeCheck = {
  question: string;
  answers: string[];
  correct: number;
  explanation: string;
};

export type CourseLesson = {
  id: string;
  title: string;
  minutes: number;
  objectives: string[];
  prerequisites: string[];
  concepts: { title: string; paragraphs: string[] }[];
  terms: [string, string][];
  method: string[];
  example: { title: string; scenario: string; steps: string[]; result: string };
  mistakes: string[];
  check: KnowledgeCheck;
  practice: { prompt: string; hint: string; answer: string };
  summary: string[];
};

export type CourseModule = {
  id: number;
  title: string;
  summary: string;
  minutes: number;
  difficulty: "Beginner" | "Intermediate" | "Advanced";
  topics: string[];
  lessons: [CourseLesson, CourseLesson];
};

const lesson = (value: CourseLesson) => value;

export const courseModules: CourseModule[] = [
  {
    id: 1,
    title: "Reliable Release Foundations",
    summary: "Turn releases from risky events into routine, repeatable work.",
    minutes: 52,
    difficulty: "Beginner",
    topics: ["cycle time", "feedback", "release candidates"],
    lessons: [
      lesson({
        id: "release-problem",
        title: "Why software releases become painful",
        minutes: 24,
        objectives: ["Define cycle time", "Recognize three release antipatterns", "Explain why infrequent releases increase risk"],
        prerequisites: ["A basic idea of source code, testing, and production"],
        concepts: [
          { title: "The delivery problem", paragraphs: ["Software creates value only when people can use it. The path from an idea to working software includes building, testing, configuring, deploying, and releasing. If that path is slow or unreliable, even a tiny change can wait weeks for production.", "Cycle time is the elapsed time from deciding to make a change until users receive it. Shortening cycle time is not about skipping controls; it is about making those controls fast, repeatable, and visible."] },
          { title: "Release antipatterns", paragraphs: ["Manual deployments depend on memory and hand-written instructions, so results vary. Testing in a production-like environment only near the end delays important feedback. Manually changing environments creates configuration drift: machines that should match slowly become different.", "Large, rare releases combine many changes. When something fails, the search area is large and the team has had little practice recovering. Small, frequent releases make each decision easier to understand and rehearse the process continually."] },
        ],
        terms: [["Cycle time", "Time from deciding on a change until that change is in use."], ["Configuration drift", "Unplanned differences between environments caused by unmanaged changes."], ["Production-like", "Managed by the same mechanisms as production, even if it has less capacity."]],
        method: ["Map every step from check-in to usable software.", "Mark queues, handoffs, approvals, and manual actions.", "Identify the earliest point where each defect could have been detected.", "Automate one repeatable bottleneck and measure cycle time again."],
        example: { title: "A one-line fix", scenario: "A critical fix takes 10 minutes to code but waits four days for a release window.", steps: ["The coding time is not the main delay.", "Manual packaging, environment setup, and approval queues dominate the path.", "Automating those repeated steps and rehearsing them on every candidate reduces both waiting and variation."], result: "The improvement target is the whole delivery path, not developer typing speed." },
        mistakes: ["Treating deployment as an operations-only responsibility", "Calling a process reliable because it worked once", "Making releases larger to reduce how often the painful process runs"],
        check: { question: "Which change most directly reduces release risk?", answers: ["Bundle more features into each release", "Use a repeatable automated process frequently", "Test only after development ends", "Keep production configuration undocumented"], correct: 1, explanation: "Frequent use of a repeatable automated process exposes problems early and gives the team regular practice." },
        practice: { prompt: "A team releases quarterly using a 40-step document. Name two risks and the first improvement you would make.", hint: "Think about variation, delayed feedback, and which step is repeated most often.", answer: "Risks include human error, configuration drift, late defect discovery, and difficult diagnosis across many changes. Start by putting the process and configuration under version control, then automate a common repeatable path." },
        summary: ["Optimize the complete path from idea to users.", "Manual, late, and environment-specific work creates avoidable risk.", "Frequent repetition turns release into a practiced routine."],
      }),
      lesson({
        id: "feedback-principles",
        title: "Feedback, release candidates, and delivery principles",
        minutes: 28,
        objectives: ["Describe the delivery feedback loop", "Define a release candidate", "Apply core software-delivery principles"],
        prerequisites: ["Why software releases become painful"],
        concepts: [
          { title: "A feedback process for every change", paragraphs: ["Every change to code, configuration, data scripts, or environments can affect releasability. Each change should therefore trigger a feedback process that tests whether the system still works and can still be released.", "Feedback has value only when it is fast, visible, and acted on. A red result that everyone ignores is not a control. The team should stop, diagnose the smallest failing stage, and restore a known-good state."] },
          { title: "A candidate at every check-in", paragraphs: ["A release candidate is a specific version that has passed enough checks to be considered for release. The goal is for every check-in to create a potential candidate, with confidence increasing as it passes later pipeline stages.", "The supporting principles are practical: automate repeatable work, keep all relevant assets in version control, build quality in, bring painful work forward and do it often, make delivery a shared responsibility, and improve the process continuously."] },
        ],
        terms: [["Feedback loop", "A change, an automated evaluation, a visible result, and a response."], ["Release candidate", "A uniquely identified version being evaluated for release."], ["Releasable", "In a verified state from which the software could be released on demand."]],
        method: ["Trigger checks for every relevant change.", "Run the fastest, most diagnostic checks first.", "Stop promotion at the first failure.", "Record the candidate and evidence produced.", "Act on the result before adding more change."],
        example: { title: "Ordering feedback", scenario: "A syntax check takes 10 seconds, unit tests 4 minutes, and capacity tests 90 minutes.", steps: ["Run the syntax check first because it is fast and can reject an invalid candidate cheaply.", "Run unit tests next for broad functional feedback.", "Run capacity tests only after earlier gates pass."], result: "Fast failures protect scarce environments and shorten the average feedback time." },
        mistakes: ["Running expensive tests before quick checks", "Allowing failed candidates to continue", "Keeping build scripts or environment definitions outside version control"],
        check: { question: "When does a feedback loop actually help?", answers: ["When the report is archived", "When the result is fast, visible, and acted on", "Only at the end of a project", "Only when every test is manual"], correct: 1, explanation: "Feedback must arrive soon enough to guide work, reach the delivery team, and cause a response." },
        practice: { prompt: "Order these gates: 2-hour capacity test, 5-minute commit tests, 20-minute acceptance tests. Explain your order.", hint: "Reject bad candidates with the cheapest useful evidence first.", answer: "Commit tests, acceptance tests, then capacity tests. Each later stage costs more, so only candidates that pass the faster gates should consume it." },
        summary: ["Every change should start a feedback process.", "Confidence in a candidate grows through ordered gates.", "A failed stage stops the line until the team restores it."],
      }),
    ],
  },
  {
    id: 2,
    title: "Configuration Management",
    summary: "Reproduce applications and environments from controlled assets.",
    minutes: 58,
    difficulty: "Beginner",
    topics: ["version control", "dependencies", "configuration"],
    lessons: [
      lesson({
        id: "everything-versioned",
        title: "Keep the whole system in version control",
        minutes: 27,
        objectives: ["Define configuration management", "List assets that belong in version control", "Explain traceability and reproducibility"],
        prerequisites: ["Reliable release foundations", "Basic version-control vocabulary"],
        concepts: [
          { title: "More than source code", paragraphs: ["Configuration management stores, retrieves, identifies, and changes every artifact and relationship needed by a system. Source code is only one part. Tests, build and deployment scripts, database changes, requirements, documentation, library versions, and environment definitions also affect the result.", "A clean checkout plus declared dependencies should contain enough information to build, test, and deploy. Generated binaries normally belong in an artifact repository rather than source control; the instructions and inputs that create them do belong in version control."] },
          { title: "Small, meaningful changes", paragraphs: ["Frequent check-ins reduce merge risk and make a failure easier to trace. A useful commit message explains why the change exists, not merely which file changed.", "Dependency versions must be explicit. Depending on an unversioned 'latest' library makes an older build impossible to reproduce and hides the cause when behavior changes."] },
        ],
        terms: [["Configuration management", "Control of project artifacts, their identities, relationships, and changes."], ["Baseline", "A known set of versions that defines a reproducible state."], ["Traceability", "The ability to connect a deployed result back to its exact inputs and changes."]],
        method: ["List every input required to build and run the system.", "Put human-created inputs and automation in version control.", "Pin external dependency versions.", "Tag or otherwise identify release baselines.", "Verify by rebuilding from a clean checkout."],
        example: { title: "Can version 2.4 be rebuilt?", scenario: "The code is tagged, but the database script is in email and the build downloads the newest library.", steps: ["The tag identifies only part of the system.", "The missing data change prevents a complete reconstruction.", "The floating dependency can produce a different binary tomorrow.", "Version both inputs and record the dependency version."], result: "A baseline is reproducible only when all relevant inputs are identified." },
        mistakes: ["Versioning source but not tests or deployment scripts", "Checking generated binaries into source control as part of each build", "Using vague commit messages such as 'updates'"],
        check: { question: "Which item should normally be version-controlled?", answers: ["Only application source", "A developer's temporary cache", "Database migration scripts", "An untracked production edit"], correct: 2, explanation: "Database changes are part of the deployable system and must be traceable and repeatable." },
        practice: { prompt: "Audit a project with source, tests, a manual server checklist, and an unpinned library. What must change?", hint: "Ask whether a clean machine can reproduce the release.", answer: "Version the server configuration or its automated script, pin the library version, and keep source and tests together. Then prove the baseline with a clean build." },
        summary: ["Configuration management covers every input to delivery.", "Explicit versions and frequent commits improve traceability.", "A clean rebuild is the practical test of reproducibility."],
      }),
      lesson({
        id: "configuration-environments",
        title: "Manage configuration and environments",
        minutes: 31,
        objectives: ["Separate configuration from packaged code", "Explain environment drift", "Design a controlled configuration change"],
        prerequisites: ["Keep the whole system in version control"],
        concepts: [
          { title: "One application, several environments", paragraphs: ["Values such as database addresses, service endpoints, and resource limits vary by environment. The application should expose these values through a controlled configuration mechanism instead of embedding them in the binary.", "Configuration needs the same discipline as code: unique identification, review, testing, access control, and history. Sensitive values need protected storage, but the names, structure, and process for supplying them remain controlled."] },
          { title: "Reproduce, do not repair by hand", paragraphs: ["Test and production need not have identical capacity, but they should be created, configured, and deployed with the same mechanisms. A manual fix on one server creates drift and knowledge that exists only in a person's memory.", "Prefer applying a small versioned change through automation. The desired state should be clear enough that a new environment can be created and an old one can be restored without detective work."] },
        ],
        terms: [["Application configuration", "Values that change how the same build behaves in a particular context."], ["Environment", "The infrastructure, software stack, application, and configuration on which a system runs."], ["Desired state", "The declared configuration an environment should have."]],
        method: ["Separate environment-specific values from the binary.", "Define names, defaults, validation, and ownership for values.", "Store ordinary configuration in version control and protect secrets appropriately.", "Apply changes with the same automated mechanism everywhere.", "Test the resulting environment and record the change."],
        example: { title: "A staging-only timeout", scenario: "An engineer logs into staging and changes a timeout from 5 to 30 seconds.", steps: ["The change is not reviewable or reproducible.", "Production may still behave differently for an unknown reason.", "Declare the value, change it through the managed process, and run the same validation used elsewhere."], result: "The environment now has a traceable state instead of a hidden exception." },
        mistakes: ["Baking production addresses into the artifact", "Assuming test must have production scale to be production-like", "Editing a running environment without recording the change"],
        check: { question: "What makes a smaller test environment production-like?", answers: ["It has the same user data", "It is managed and deployed with the same mechanisms", "It costs the same", "It is edited by the same administrator"], correct: 1, explanation: "Consistency of management, configuration, and deployment matters even when capacity differs." },
        practice: { prompt: "Design a safe change for an environment-specific connection timeout.", hint: "Include identification, review, application, and verification.", answer: "Change the declared value in its controlled store, review it, apply it with the common deployment mechanism, run a smoke test, and record which environment and version received it." },
        summary: ["Keep environment-specific values outside the binary.", "Use one mechanism to configure every environment.", "Replace manual repair with versioned, testable state changes."],
      }),
    ],
  },
  {
    id: 3,
    title: "Continuous Integration",
    summary: "Integrate small changes often and keep the application working.",
    minutes: 56,
    difficulty: "Beginner",
    topics: ["mainline", "commit tests", "broken build"],
    lessons: [
      lesson({
        id: "ci-loop",
        title: "The continuous integration loop",
        minutes: 26,
        objectives: ["Define continuous integration", "Describe its prerequisites", "Trace the check-in feedback loop"],
        prerequisites: ["Configuration management", "An automated build and basic tests"],
        concepts: [
          { title: "Integrate every change", paragraphs: ["Continuous integration means that each change is integrated into the shared mainline, the whole application is built, and a comprehensive set of fast automated tests runs. The goal is to keep the software working, not merely to collect build reports.", "CI needs a version-controlled system, an automated build, commit tests, and a team willing to integrate frequently. Long-lived branches postpone integration and allow conflicts and incompatible assumptions to accumulate."] },
          { title: "A tight loop", paragraphs: ["A developer updates from mainline, makes a small change, runs commit tests, checks in, and waits for the CI result. If it passes, the shared state remains trusted. If it fails, repairing or reverting the change becomes the team's immediate priority.", "A short build keeps this discipline practical. Slow tests should be moved to later stages or improved, while the commit stage retains enough coverage to catch common regressions."] },
        ],
        terms: [["Mainline", "The shared line of development that represents the integrated system."], ["Commit tests", "Fast automated tests that evaluate every change."], ["Integration", "Combining a change with the rest of the system and proving they work together."]],
        method: ["Update from mainline.", "Make one small coherent change.", "Run commit tests locally.", "Check in and let CI rebuild from a clean workspace.", "Wait for the result and fix or revert any failure immediately."],
        example: { title: "Two developers, one interface", scenario: "One developer renames a method while another calls its old name on a week-long branch.", steps: ["The delayed merge hides the incompatibility for a week.", "Daily mainline integration reveals it near the first change.", "The smaller difference is quicker to diagnose and coordinate."], result: "CI reduces integration risk by shrinking the time and change set between integrations." },
        mistakes: ["Calling a nightly build continuous integration", "Checking in without observing the result", "Using CI to compensate for an unreproducible local build"],
        check: { question: "What is the primary goal of CI?", answers: ["Keep the software in a working state", "Create longer-lived branches", "Replace all manual testing", "Deploy every build to users"], correct: 0, explanation: "CI continuously demonstrates that the integrated application still works at the tested level." },
        practice: { prompt: "A team merges every two weeks and runs tests nightly. Give two changes needed for CI.", hint: "Focus on integration frequency and per-change feedback.", answer: "Integrate small changes to mainline at least daily and trigger the automated build and commit tests on every check-in. The team must also act immediately on failures." },
        summary: ["CI integrates and tests every small change.", "Frequent mainline work prevents a late integration phase.", "The loop ends only when the team responds to the result."],
      }),
      lesson({
        id: "green-build",
        title: "Keep the build green",
        minutes: 30,
        objectives: ["Respond safely to a broken build", "Apply time-boxed diagnosis", "Improve the usefulness of CI feedback"],
        prerequisites: ["The continuous integration loop"],
        concepts: [
          { title: "Stop the line", paragraphs: ["A broken build removes the team's evidence that the mainline works. Do not add unrelated changes on top of it. The person whose change exposed the problem leads the repair, but the state of the build belongs to everyone.", "Begin with the first failing check, reproduce it, and compare with the last good revision. If a quick correction is not clear, revert the change to restore service, then investigate on a separate change."] },
          { title: "Useful feedback", paragraphs: ["A build should report which revision ran, which stage failed, and how to reproduce the failure. Visible status helps the team respond; noisy or flaky results teach people to ignore the system.", "Do not comment out a failing test merely to make the dashboard green. Either fix the product, fix a genuinely incorrect test, or revert the triggering change while preserving the evidence."] },
        ],
        terms: [["Broken build", "A mainline revision that fails its required build or commit tests."], ["Revert", "A new change that restores the previous behavior by undoing a revision."], ["Flaky test", "A test that passes and fails without a relevant product change."]],
        method: ["Stop new check-ins.", "Read the earliest useful failure.", "Reproduce against the same revision.", "Time-box the fix.", "Fix quickly or revert, then verify the mainline is green."],
        example: { title: "A failure at day's end", scenario: "A commit breaks three tests 15 minutes before the author leaves.", steps: ["The author should not leave the mainline broken.", "If the cause is obvious, fix and rerun.", "If not, revert the commit and confirm the build, then resume investigation later."], result: "The team regains a trustworthy mainline without hiding the defect." },
        mistakes: ["Starting new work while mainline is red", "Disabling the failing test", "Spending hours debugging while everyone is blocked instead of reverting"],
        check: { question: "What should happen when a quick fix is not clear?", answers: ["Ignore the result", "Queue more commits", "Revert to the last good state", "Delete the test suite"], correct: 2, explanation: "Time-boxing and reverting restores the shared working state while investigation continues safely." },
        practice: { prompt: "Write a five-step response to a failing mainline build.", hint: "Preserve evidence and restore the shared state quickly.", answer: "Stop check-ins; inspect the first failure; reproduce the same revision; time-box a correction; then fix or revert and verify the complete commit stage passes." },
        summary: ["A red mainline is a team-level incident.", "Fix quickly or revert to restore trust.", "Reliable, diagnostic results are more valuable than a merely green display."],
      }),
    ],
  },
  {
    id: 4,
    title: "Testing Strategy",
    summary: "Build quality in with layered automated and exploratory feedback.",
    minutes: 61,
    difficulty: "Beginner",
    topics: ["unit tests", "acceptance tests", "exploratory testing"],
    lessons: [
      lesson({
        id: "test-feedback",
        title: "Choose tests by the feedback they provide",
        minutes: 30,
        objectives: ["Classify tests by purpose", "Balance automated and manual testing", "Explain why testing starts with development"],
        prerequisites: ["Continuous integration"],
        concepts: [
          { title: "Tests have different jobs", paragraphs: ["Technology-facing tests support development by checking small units, components, and integration points. Business-facing tests support development by expressing examples of desired behavior. Other tests critique the product: exploratory, usability, security, and capacity testing reveal risks that scripted functional examples may miss.", "No single layer is sufficient. Fast unit tests localize coding errors; acceptance tests show that valuable behavior works; exploratory work uses human judgment to discover surprises."] },
          { title: "Build quality in", paragraphs: ["Testing is not a phase after coding. Developers, testers, and users collaborate from the beginning, and automated tests run whenever the system changes. This creates feedback while the relevant work is still small and familiar.", "Manual testing remains essential, especially for exploration and usability. Automation handles repeatable checks so people can spend attention on learning and judgment."] },
        ],
        terms: [["Unit test", "A fast test of a small piece of behavior in isolation."], ["Acceptance test", "A business-facing example that demonstrates required system behavior."], ["Exploratory testing", "Simultaneous learning, test design, and execution guided by human observation."]],
        method: ["Name the risk or question.", "Choose the smallest test level that can answer it.", "Automate repeatable checks.", "Use exploration for unknown risks and usability.", "Run each test at the earliest useful stage."],
        example: { title: "Testing a checkout discount", scenario: "A rule gives 10% off orders over $100.", steps: ["Unit examples check boundary calculations quickly.", "An acceptance example checks the customer-visible total through the application boundary.", "Exploratory testing probes currency, rounding, and unusual cart changes."], result: "Each test supplies different evidence; together they cover both specified behavior and surprises." },
        mistakes: ["Relying only on end-to-end UI tests", "Deferring testing until a test phase", "Assuming automation removes the need for exploratory work"],
        check: { question: "Which activity is best suited to human exploratory testing?", answers: ["Repeating the same calculation on every commit", "Discovering surprising behavior around an unfamiliar workflow", "Compiling the application", "Checking a fixed formatting rule"], correct: 1, explanation: "Exploration uses human learning and judgment where the important questions are not fully known in advance." },
        practice: { prompt: "Choose tests for a password-reset feature and justify each level.", hint: "Include a small rule, a business flow, and an unknown-risk activity.", answer: "Use unit tests for token expiry rules, acceptance tests for requesting and completing a reset, integration tests for the mail boundary, and exploratory/security testing for abuse, confusing messages, and unusual navigation." },
        summary: ["Select tests according to the feedback needed.", "Automated and manual testing complement one another.", "Testing throughout development prevents a late quality phase."],
      }),
      lesson({
        id: "testing-existing-systems",
        title: "Grow a practical test strategy",
        minutes: 31,
        objectives: ["Start testing in new and legacy systems", "Use test doubles appropriately", "Manage defects as planned work"],
        prerequisites: ["Choose tests by the feedback they provide"],
        concepts: [
          { title: "Start where risk is highest", paragraphs: ["A new project can establish testability and automated acceptance examples from its first feature. An existing or legacy system needs an incremental approach: place tests around behavior being changed, important business paths, and recurring defects.", "Test doubles replace slow or unavailable collaborators for focused tests. They help isolate behavior, but too many mocks tied to implementation details make tests fragile and can hide integration problems."] },
          { title: "Defects are information", paragraphs: ["Classify defects by severity, frequency, user impact, and available workaround. Put them in the same prioritized backlog as features so the team makes an explicit value decision.", "Every escaped defect suggests a missing feedback loop. Add the cheapest reliable test that would have detected it, at the lowest appropriate level."] },
        ],
        terms: [["Test double", "A controlled replacement for a real collaborator during a test."], ["Regression test", "A test that protects behavior from being broken by later changes."], ["Defect backlog", "Prioritized defects managed alongside other delivery work."]],
        method: ["Identify a valuable path or current change.", "Add a characterization or acceptance test around existing behavior.", "Refactor only with that protection.", "Add focused lower-level tests as seams become available.", "Turn escaped defects into regression tests."],
        example: { title: "Changing a legacy invoice", scenario: "No tests exist and a tax calculation must change.", steps: ["Capture current examples around unaffected invoice behavior.", "Write a failing example for the new tax rule.", "Create a seam around the calculation and add focused tests.", "Keep an integration example for the complete invoice."], result: "Coverage grows around real change without requiring a risky rewrite first." },
        mistakes: ["Demanding complete coverage before any legacy change", "Mocking every class interaction", "Keeping defects in a separate list with no business priority"],
        check: { question: "What is a strong first move in an untested legacy system?", answers: ["Rewrite it completely", "Add tests around the behavior you are about to change", "Wait for a test phase", "Mock every dependency"], correct: 1, explanation: "Incremental protection around active change gives immediate value and creates a safe path for improvement." },
        practice: { prompt: "A production defect rounds totals incorrectly. Describe the feedback improvement.", hint: "Reproduce first, then choose the lowest useful test level.", answer: "Add a failing example that reproduces the rounding case, preferably as a focused unit test plus an acceptance example if the user-visible result matters. Fix it, keep the tests, and prioritize any related defects." },
        summary: ["Grow tests around valuable behavior and active change.", "Use doubles for isolation without losing integration evidence.", "Treat every escaped defect as guidance for a better feedback loop."],
      }),
    ],
  },
  {
    id: 5,
    title: "The Deployment Pipeline",
    summary: "Move every candidate through visible, increasingly rigorous gates.",
    minutes: 63,
    difficulty: "Beginner",
    topics: ["commit stage", "promotion", "artifacts"],
    lessons: [
      lesson({
        id: "pipeline-anatomy",
        title: "Anatomy of a deployment pipeline",
        minutes: 30,
        objectives: ["Define a deployment pipeline", "Explain staged confidence", "Distinguish a candidate from an environment"],
        prerequisites: ["Continuous integration", "Testing strategy"],
        concepts: [
          { title: "The path from check-in to release", paragraphs: ["A deployment pipeline is an automated implementation of the build, deploy, test, and release process. Every change creates a pipeline instance and therefore a visible record of the candidate's progress.", "Fast commit tests reject obvious failures first. Passing candidates move to acceptance, nonfunctional, and manual evaluation. Later stages are slower or require scarce environments, so they run only after cheaper gates provide confidence."] },
          { title: "One candidate, increasing evidence", paragraphs: ["The pipeline should build binaries once and promote that same artifact. Rebuilding for staging or production introduces an untested difference.", "A candidate is not copied blindly: each stage deploys it using the standard mechanism, verifies the deployment with smoke tests, and records the outcome. A failure stops further promotion."] },
        ],
        terms: [["Deployment pipeline", "Automated build, deploy, test, and release process for each change."], ["Gate", "A required evaluation that controls promotion."], ["Promotion", "Advancing the same candidate to a later stage after evidence passes."]],
        method: ["Create a candidate from every change.", "Run the commit stage.", "Publish the uniquely identified artifact.", "Deploy it to a controlled environment.", "Run broader tests and promote only on success."],
        example: { title: "Candidate 1842", scenario: "A candidate passes unit tests but fails an acceptance example.", steps: ["The artifact remains identifiable in the repository.", "The failing acceptance gate marks this pipeline instance unsuitable for release.", "No production deployment starts.", "A corrective change creates a new candidate and a new evidence trail."], result: "The pipeline prevents a partially verified candidate from moving forward." },
        mistakes: ["Treating the pipeline as one giant script", "Rebuilding the candidate for each environment", "Allowing a later stage to run after an earlier failure"],
        check: { question: "Why are expensive tests placed later?", answers: ["They matter less", "Only candidates with cheaper evidence should consume costly resources", "They cannot be automated", "They must run after release"], correct: 1, explanation: "Ordered gates shorten feedback and protect scarce time and environments." },
        practice: { prompt: "Sketch a pipeline for a web service using four gates.", hint: "Start fast and increase scope and cost.", answer: "Commit build and unit tests; automated acceptance tests; capacity/security or exploratory evaluation; then a release decision. Build once, deploy consistently, smoke-test each deployment, and stop on failure." },
        summary: ["A pipeline gives every change a visible route to release.", "Confidence increases through ordered gates.", "Build once and promote the same identified artifact."],
      }),
      lesson({
        id: "pipeline-practices",
        title: "Promotion, smoke tests, and stopping the line",
        minutes: 33,
        objectives: ["Apply core pipeline practices", "Define a smoke test", "Plan a walking-skeleton implementation"],
        prerequisites: ["Anatomy of a deployment pipeline"],
        concepts: [
          { title: "Reliable promotion", paragraphs: ["Use the same deployment mechanism in every environment. This makes routine test deployments rehearsals for production. After deployment, a small smoke suite checks that the application starts, connects to essential services, and performs a critical transaction.", "Test environments should be production-like in topology and management. They may be smaller, but a different deployment process leaves production-specific risk untested."] },
          { title: "Start with a walking skeleton", paragraphs: ["A walking skeleton is the thinnest end-to-end path through build, deployment, test, and release. It proves the pipeline architecture before every test or feature exists.", "Model the current value stream, automate the build and deployment path, add unit/code analysis and acceptance gates, then evolve using observed bottlenecks and quality data."] },
        ],
        terms: [["Smoke test", "A short post-deployment check of essential operation."], ["Walking skeleton", "A minimal end-to-end implementation of the delivery path."], ["Pipeline instance", "The stages and evidence associated with one candidate."],
        ],
        method: ["Map the value stream.", "Create one end-to-end automated path.", "Deploy with one mechanism everywhere.", "Smoke-test every deployment.", "Stop on failure and evolve the weakest stage."],
        example: { title: "A successful install that cannot serve traffic", scenario: "The deployment command exits successfully, but the service cannot reach its database.", steps: ["Script success proves only that the installer completed.", "A smoke test exercises startup and a minimal database-backed request.", "That failure blocks promotion and points to environment or configuration diagnosis."], result: "Deployment verification tests the running result, not only the command exit code." },
        mistakes: ["Equating a successful copy command with a working deployment", "Using a special untested production script", "Waiting to design the pipeline until the product is complete"],
        check: { question: "What should a smoke test prove?", answers: ["Every edge case", "The deployment's essential functions are alive", "Only that files exist", "That users approved the release"], correct: 1, explanation: "Smoke tests are deliberately small checks that the deployed system can perform critical operations." },
        practice: { prompt: "Define a three-check smoke suite for an order service.", hint: "Cover startup, an essential dependency, and one critical path.", answer: "Check the health endpoint, perform a database-backed read, and create then retrieve a minimal test order. Keep it fast, repeatable, and safe in every environment." },
        summary: ["Deploy and verify the same way everywhere.", "Smoke tests validate the running application.", "A walking skeleton lets the pipeline grow incrementally."],
      }),
    ],
  },
  {
    id: 6,
    title: "Build and Deployment Automation",
    summary: "Create repeatable scripts that work safely in every environment.",
    minutes: 60,
    difficulty: "Intermediate",
    topics: ["scripts", "idempotency", "traceability"],
    lessons: [
      lesson({
        id: "scripted-stages",
        title: "Script every pipeline stage",
        minutes: 28,
        objectives: ["Design stage-level commands", "Choose repeatable automation boundaries", "Explain why local and CI commands should match"],
        prerequisites: ["The deployment pipeline", "Basic command-line use"],
        concepts: [
          { title: "Automation is the executable process", paragraphs: ["Each pipeline stage should have a command that can be run outside the CI server. The server coordinates stages; versioned scripts define how the application is built, tested, packaged, and deployed.", "Use the same scripts on developer machines and CI where practical. This shortens diagnosis and prevents the server configuration from becoming the only place that knows how delivery works."] },
          { title: "Small interfaces between stages", paragraphs: ["Separate compile, unit test, package, deploy, and smoke-test targets. Each target has clear inputs, outputs, and failure behavior. Avoid hidden absolute paths or machine-specific state.", "Use a technology appropriate to the deployment target and standard operating-system packaging where useful. The principle is repeatability, not loyalty to a particular tool."] },
        ],
        terms: [["Build target", "A named, repeatable automation task with defined inputs and outputs."], ["Relative path", "A location resolved from the project rather than one machine's fixed directory."], ["Orchestration", "Coordinating stage order and resources without hiding stage logic."],
        ],
        method: ["Name one command per stage.", "Declare its inputs and output.", "Remove interactive and machine-specific assumptions.", "Return a clear failure status.", "Run the same command locally and in CI."],
        example: { title: "The CI-only build", scenario: "A build works on the CI server but no developer can reproduce it.", steps: ["Critical commands are stored in the server's UI.", "Move those commands into versioned project scripts.", "Let CI call the same stage target developers can run."], result: "Build knowledge becomes reviewable and reproducible." },
        mistakes: ["Embedding all logic in a CI product's interface", "Using absolute paths", "Combining every stage into one command with no diagnostic boundary"],
        check: { question: "Where should build behavior primarily live?", answers: ["In a versioned script callable outside CI", "Only in a server administrator's notes", "In each developer's shell history", "In production by hand"], correct: 0, explanation: "Versioned scripts make the process portable, reviewable, and reproducible." },
        practice: { prompt: "Split a single 'release' script into useful targets.", hint: "Use pipeline evidence boundaries.", answer: "Create targets such as compile, unit-test, package, deploy, smoke-test, and release. Define artifacts between them and make each return a clear status." },
        summary: ["CI coordinates; versioned scripts implement.", "Stage commands need clear inputs, outputs, and failures.", "Portable commands make feedback easier to reproduce."],
      }),
      lesson({
        id: "idempotent-deployment",
        title: "Idempotency, traceability, and safe evolution",
        minutes: 32,
        objectives: ["Define idempotent deployment", "Trace binaries to source", "Improve automation incrementally"],
        prerequisites: ["Script every pipeline stage"],
        concepts: [
          { title: "Safe to repeat", paragraphs: ["An idempotent deployment produces the intended state whether it runs once or repeatedly. It checks current state and applies only necessary changes instead of assuming a pristine machine.", "Idempotency makes retries and recovery safer. It does not mean ignoring errors: the script must still fail when it cannot establish the declared state."] },
          { title: "Know exactly what is running", paragraphs: ["Every binary should carry or be associated with a build identifier that connects it to source revision, dependencies, and pipeline results. Store the binary in an artifact repository; do not rebuild it later.", "Evolve deployment automation in small verified steps. Replace one manual action, test it in lower environments, and keep a rollback or remediation path while confidence grows."] },
        ],
        terms: [["Idempotent", "Produces the same intended state when safely repeated."], ["Artifact repository", "Versioned storage for build outputs and their metadata."], ["Build identifier", "A unique value connecting an artifact to its source and evidence."],
        ],
        method: ["Inspect the current state.", "Compare it with the declared target.", "Apply only required changes.", "Verify the final state with a smoke test.", "Record artifact and source identifiers."],
        example: { title: "Retrying after a network timeout", scenario: "A deployment copied the binary but timed out before reporting success.", steps: ["A blind retry might duplicate an action or corrupt state.", "An idempotent script detects the correct binary is already present.", "It completes missing configuration and verification only."], result: "The retry converges on the desired state without guessing what happened." },
        mistakes: ["Treating every retry as a fresh install", "Producing artifacts with no source revision", "Replacing the entire deployment process in one untested change"],
        check: { question: "What does an idempotent deployment do on a safe retry?", answers: ["Always duplicates every action", "Converges on the same intended state", "Skips verification", "Builds a different artifact"], correct: 1, explanation: "It detects existing correct state and applies only what is needed to reach the declared result." },
        practice: { prompt: "Make a 'create directory, copy binary, start service' deployment retry-safe.", hint: "Check state before each operation and verify after it.", answer: "Ensure the directory exists without failing if present, compare and install the identified binary, restart only when required, then verify the service and record the deployed build." },
        summary: ["Idempotent scripts make retries safer.", "Every running binary should trace to one source revision and evidence set.", "Improve deployment automation through small rehearsed changes."],
      }),
    ],
  },
  {
    id: 7,
    title: "The Commit Stage",
    summary: "Reject bad changes quickly and publish trusted build outputs.",
    minutes: 55,
    difficulty: "Intermediate",
    topics: ["fast feedback", "code analysis", "artifact repository"],
    lessons: [
      lesson({
        id: "fast-commit-stage",
        title: "Design a fast, useful commit stage",
        minutes: 27,
        objectives: ["State the commit stage's purpose", "Choose checks that belong there", "Balance coverage and speed"],
        prerequisites: ["Continuous integration", "Build automation"],
        concepts: [
          { title: "The first pipeline gate", paragraphs: ["The commit stage compiles, runs fast unit tests, performs code analysis, and packages the candidate. It should give developers high-value feedback within minutes.", "A failure should say what broke and how to reproduce it. Checks that are slow, fragile, or need complex environments belong in later stages unless they can be redesigned."] },
          { title: "What should break it", paragraphs: ["Compilation errors, failing commit tests, serious static-analysis findings, and packaging failures should reject the change. Teams may also treat warnings or architectural rules as failures when those rules are stable and actionable.", "Tend the stage like a product: remove flakiness, track duration, and keep developers responsible for its health."] },
        ],
        terms: [["Commit stage", "The fast first pipeline stage triggered by each change."], ["Static analysis", "Automated inspection of code without executing its business behavior."], ["Fast feedback", "Evidence delivered soon enough to guide the current work."],
        ],
        method: ["Compile from a clean checkout.", "Run fast deterministic tests.", "Run useful code analysis.", "Package and label the candidate.", "Publish results and reject on any required failure."],
        example: { title: "A 45-minute commit stage", scenario: "UI tests dominate the stage and developers batch changes while waiting.", steps: ["Slow feedback weakens integration discipline.", "Keep focused unit and analysis checks in the commit stage.", "Move broad UI scenarios to the acceptance stage and improve their design."], result: "The first gate returns to minutes while later evidence remains available." },
        mistakes: ["Maximizing test count without considering feedback time", "Keeping flaky checks in the critical first gate", "Reporting only 'build failed'"],
        check: { question: "Which check best fits the commit stage?", answers: ["A two-hour capacity test", "A fast deterministic unit suite", "A week of user acceptance", "A production release approval"], correct: 1, explanation: "The commit stage prioritizes fast, broad, diagnostic feedback on every change." },
        practice: { prompt: "A stage takes 35 minutes: compile 3, unit 5, UI 25, package 2. Redesign it.", hint: "Preserve the fastest useful gate and move broader evidence later.", answer: "Keep compile, unit tests, useful analysis, and package in the commit stage. Move the UI suite to acceptance, then improve or parallelize it. The first result can arrive in roughly 10 minutes." },
        summary: ["The commit stage is the fastest serious gate.", "Include deterministic checks with actionable failures.", "Measure and tend stage health continuously."],
      }),
      lesson({
        id: "commit-artifacts",
        title: "Artifacts and commit-test design",
        minutes: 28,
        objectives: ["Describe commit-stage outputs", "Design fast unit tests", "Explain artifact metadata"],
        prerequisites: ["Design a fast, useful commit stage"],
        concepts: [
          { title: "Outputs other stages can trust", paragraphs: ["A successful commit stage produces a uniquely identified package plus reports: test results, analysis, source revision, and dependency information. Later stages retrieve this candidate rather than rebuilding it.", "The repository needs retention and access rules, but its central promise is simple: given an identifier, the exact tested output can be found."] },
          { title: "Keep commit tests focused", paragraphs: ["Fast tests avoid user interfaces, databases, network calls, and timing where those dependencies are not the behavior under test. Dependency injection and test doubles can isolate code.", "Isolation is not the entire strategy. Later integration and acceptance stages must verify the real boundaries that focused tests replace."] },
        ],
        terms: [["Artifact", "A versioned build output promoted through later stages."], ["Dependency injection", "Supplying collaborators from outside an object so tests can control them."], ["Test report", "Recorded evidence about which tests ran and their outcomes."],
        ],
        method: ["Build the package once.", "Assign a unique identifier.", "Attach revision, dependency, and result metadata.", "Publish only after required checks pass.", "Retrieve that same package in later stages."],
        example: { title: "Finding what production runs", scenario: "Production reports version 1842.", steps: ["Look up artifact 1842 in the repository.", "Read its source revision and dependency manifest.", "Open its commit and later-stage reports.", "Use that evidence to reproduce or roll back."], result: "The identifier connects an operating system back to its exact tested inputs." },
        mistakes: ["Rebuilding from the same source and assuming the binary is identical", "Using real networks in every unit test", "Publishing an artifact before required checks pass"],
        check: { question: "What should production and acceptance testing share?", answers: ["Only a source tag", "The exact same built artifact", "A manually recreated package", "Different dependency versions"], correct: 1, explanation: "Promoting one artifact prevents untested differences caused by rebuilding." },
        practice: { prompt: "List metadata required for a traceable web-service artifact.", hint: "Connect output, inputs, and evidence.", answer: "Include a unique build identifier, source revision, dependency versions, build time/tool version where relevant, and links to commit-stage test and analysis results." },
        summary: ["The commit stage publishes one identifiable candidate.", "Fast tests isolate unnecessary external boundaries.", "Artifact metadata connects running software to source and evidence."],
      }),
    ],
  },
  {
    id: 8,
    title: "Automated Acceptance Testing",
    summary: "Turn business examples into durable executable specifications.",
    minutes: 65,
    difficulty: "Intermediate",
    topics: ["acceptance criteria", "test layers", "parallel tests"],
    lessons: [
      lesson({
        id: "executable-specifications",
        title: "Acceptance tests as executable specifications",
        minutes: 31,
        objectives: ["Define acceptance tests", "Create concrete acceptance criteria", "Separate business language from technical details"],
        prerequisites: ["Testing strategy", "Deployment pipeline"],
        concepts: [
          { title: "Examples before implementation", paragraphs: ["Acceptance tests express whether a feature delivers the behavior users need. Developers, testers, and business representatives agree on concrete examples before implementation, making ambiguous requirements visible early.", "Passing examples demonstrate required behavior and become regression protection. They do not prove the absence of every defect, so exploration and lower-level tests remain necessary."] },
          { title: "A layered test design", paragraphs: ["Keep business-readable scenarios separate from the driver that operates the application. The driver translates domain actions such as 'place an order' into API or UI calls. This limits change when the interface moves.", "Prefer testing below the user interface when the same behavior can be observed through a stable boundary. Keep a smaller set of UI scenarios for genuine interface behavior."] },
        ],
        terms: [["Executable specification", "A concrete behavior example that can run against the system."], ["Application driver", "A test layer translating domain actions into technical interaction."], ["Acceptance criterion", "An observable condition that must hold for a feature to be accepted."],
        ],
        method: ["Discuss a user outcome.", "Write concrete examples including boundaries and errors.", "Express them in domain language.", "Automate through a stable driver layer.", "Run the suite against every candidate."],
        example: { title: "Free delivery", scenario: "Orders of $50 or more receive free standard delivery.", steps: ["Example below boundary: $49.99 retains the fee.", "Example at boundary: $50.00 has no fee.", "Example above boundary: $75.00 has no fee.", "Keep calculation details out of the scenario wording."], result: "The examples clarify the rule before code and remain readable afterward." },
        mistakes: ["Writing acceptance tests only after the feature is complete", "Encoding CSS selectors throughout business scenarios", "Using one happy-path example as complete coverage"],
        check: { question: "Why use an application-driver layer?", answers: ["To make tests longer", "To isolate business scenarios from interface details", "To avoid all integration", "To replace acceptance criteria"], correct: 1, explanation: "A driver localizes technical interaction so readable specifications survive interface changes." },
        practice: { prompt: "Write three acceptance examples for a five-attempt account lock.", hint: "Cover below, at, and after the boundary.", answer: "Four failed attempts leave login available; the fifth failed attempt locks the account; a correct password after lock is refused until the defined unlock process succeeds." },
        summary: ["Acceptance tests make agreed examples executable.", "Concrete boundaries expose ambiguity early.", "A driver layer keeps business language separate from interface mechanics."],
      }),
      lesson({
        id: "acceptance-suite",
        title: "Build a maintainable acceptance suite",
        minutes: 34,
        objectives: ["Control test data and isolation", "Diagnose asynchronous behavior", "Scale a suite without losing reliability"],
        prerequisites: ["Acceptance tests as executable specifications"],
        concepts: [
          { title: "Reliable and independent", paragraphs: ["Each test should establish the data it needs and leave the system in a known state. Tests that depend on execution order or shared mutable records fail unpredictably and are difficult to parallelize.", "External systems can be replaced at controlled boundaries when they are slow or unavailable, but keep separate integration checks to prove the contract."] },
          { title: "Wait for conditions, not time", paragraphs: ["Asynchronous systems may complete later. Fixed sleeps are both slow and unreliable. Poll for an observable condition with a clear timeout, then report the state seen when the timeout expires.", "Parallel execution reduces elapsed time only when tests are isolated and environments have capacity. Track flakiness as a defect; an ignored red suite is no gate at all."] },
        ],
        terms: [["Isolation", "A test controls its state and does not depend on other test outcomes."], ["Timeout", "A clear upper bound after which an unmet condition becomes a failure."], ["Parallel execution", "Running independent tests concurrently to reduce elapsed time."],
        ],
        method: ["Create unique test data.", "Exercise behavior through the driver.", "Observe a stable business result.", "Clean up or reset state.", "Parallelize only after independence is proven."],
        example: { title: "Waiting for an email", scenario: "A test sleeps 30 seconds after requesting a message.", steps: ["The email may arrive in 2 seconds, wasting 28.", "Under load it may arrive in 31 seconds, causing a false failure.", "Poll the controlled mail boundary for the message until a meaningful timeout."], result: "The test finishes as soon as evidence appears and fails with useful context when it does not." },
        mistakes: ["Sharing one customer record across the suite", "Using arbitrary sleeps", "Accepting flaky tests as normal"],
        check: { question: "What is the best way to test eventual completion?", answers: ["Sleep for a guessed duration", "Poll an observable condition with a timeout", "Run the test twice", "Ignore the result"], correct: 1, explanation: "Condition-based waiting is faster when the result arrives early and clearer when it never arrives." },
        practice: { prompt: "A parallel suite collides on username 'test-user'. Fix the design.", hint: "Give each test ownership of its data.", answer: "Generate a unique username per test, create it through a controlled setup path, avoid order dependencies, and clean up or reset the isolated state." },
        summary: ["Independent test data enables reliable parallelism.", "Wait on observable conditions with explicit timeouts.", "Treat flaky automation as a product defect."],
      }),
    ],
  },
  {
    id: 9,
    title: "Nonfunctional Requirements",
    summary: "Test capacity, security, availability, and other service qualities.",
    minutes: 62,
    difficulty: "Intermediate",
    topics: ["capacity", "service levels", "test environments"],
    lessons: [
      lesson({
        id: "service-qualities",
        title: "Make service qualities testable",
        minutes: 29,
        objectives: ["Distinguish functional and nonfunctional requirements", "Write measurable acceptance criteria", "Identify representative workloads"],
        prerequisites: ["Automated acceptance testing"],
        concepts: [
          { title: "How well must it work?", paragraphs: ["Functional requirements describe behavior; nonfunctional requirements describe qualities and constraints such as capacity, availability, security, and maintainability. Vague words like 'fast' cannot guide design or acceptance.", "Express a service quality with a workload, a measurable threshold, and operating conditions. Include both normal and peak behavior plus the expected response when limits are exceeded."] },
          { title: "Capacity is a system property", paragraphs: ["Response time depends on concurrency, request mix, data volume, hardware, and external services. A single request on a developer laptop does not predict production capacity.", "Capacity testing should begin early enough to influence architecture and run again when changes affect important paths. Results are evidence about a specific setup, not timeless guarantees."] },
        ],
        terms: [["Nonfunctional requirement", "A measurable quality or constraint on system operation."], ["Throughput", "Work completed per unit of time."], ["Latency", "Elapsed time for one operation or response."],
        ],
        method: ["Name the user or business outcome.", "Define workload and data volume.", "Choose measurable latency, throughput, or failure thresholds.", "State the environment and duration.", "Define success and overload behavior."],
        example: { title: "Replace 'the search must be fast'", scenario: "The requirement contains no load or threshold.", steps: ["Specify 200 concurrent users and a representative query mix.", "Require 95% of searches to complete within 2 seconds for 30 minutes.", "State the data volume and acceptable error rate."], result: "The requirement is now testable and tied to an operating context." },
        mistakes: ["Using only average response time", "Leaving data volume unspecified", "Treating one successful run as a permanent guarantee"],
        check: { question: "Which requirement is testable?", answers: ["Pages should be fast", "Most users should be happy", "At 100 concurrent users, 95% of reads finish within 1 second", "The system should scale"], correct: 2, explanation: "It defines workload, a percentile, and a measurable latency threshold." },
        practice: { prompt: "Rewrite 'checkout must handle peak traffic' as measurable criteria.", hint: "Include concurrency or rate, duration, threshold, data, and errors.", answer: "For example: with production-like catalog data and 300 concurrent checkout users for 20 minutes, 95% of submissions complete within 2 seconds and errors remain below 0.5%." },
        summary: ["Service qualities need measurable operating conditions.", "Workload, data, and environment shape results.", "Begin nonfunctional testing early enough to change the design."],
      }),
      lesson({
        id: "capacity-tests",
        title: "Design and interpret capacity tests",
        minutes: 33,
        objectives: ["Build a capacity-test plan", "Avoid coordinated test errors", "Interpret evidence without overclaiming"],
        prerequisites: ["Make service qualities testable"],
        concepts: [
          { title: "A controlled experiment", paragraphs: ["Use a production-like topology and known configuration. Generate a realistic mix of operations, warm the system where appropriate, then measure steady behavior. Monitor the load generator too; it can become the bottleneck.", "Change one important variable at a time when diagnosing capacity. Record application version, environment, data set, workload, metrics, and anomalies so another person can interpret the run."] },
          { title: "Learn the shape of failure", paragraphs: ["Run tests at expected load, peak load, and beyond the target. Observe where latency rises, errors appear, or a resource saturates. Recovery after load matters as much as the first threshold crossing.", "A result supports a claim only for the tested conditions. Use trends across repeated runs to detect regressions rather than comparing unrelated environments."] },
        ],
        terms: [["Load generator", "A tool or process that creates the test workload."], ["Saturation", "A resource reaching a limit so additional demand increases delay or errors."], ["Baseline", "A recorded reference run used for meaningful comparison."],
        ],
        method: ["Define acceptance criteria.", "Prepare controlled environment and data.", "Warm up, then apply the workload.", "Measure users, application, dependencies, and generator.", "Repeat and compare with the baseline."],
        example: { title: "A sudden latency wall", scenario: "Latency is stable to 150 users, then climbs sharply while database connections reach their limit.", steps: ["The correlation suggests a database pool constraint.", "Repeat with controlled pool changes rather than assuming causation.", "Verify throughput, errors, and recovery in each run."], result: "The experiment turns a symptom into a testable capacity hypothesis." },
        mistakes: ["Running the load generator on an overloaded laptop", "Changing code, hardware, and data between comparison runs", "Reporting an average without percentiles or errors"],
        check: { question: "What should remain controlled when comparing two runs?", answers: ["Everything except the variable under study", "Nothing", "Only the chart color", "The conclusion"], correct: 0, explanation: "Controlled comparisons make it possible to connect an outcome to the change being evaluated." },
        practice: { prompt: "A result says '2,000 requests/second' with no other data. What is missing?", hint: "Ask what ran, where, for how long, and with what quality.", answer: "It needs version, environment, request mix, concurrency, data volume, duration, latency percentiles, errors, resource metrics, load-generator health, and baseline context." },
        summary: ["Capacity tests are controlled experiments.", "Measure the generator and dependencies as well as the application.", "Claims must stay within the tested conditions."],
      }),
    ],
  },
  {
    id: 10,
    title: "Deploying and Releasing",
    summary: "Separate technical deployment from user release and recover safely.",
    minutes: 67,
    difficulty: "Intermediate",
    topics: ["deployment", "release", "rollback"],
    lessons: [
      lesson({
        id: "deploy-vs-release",
        title: "Deploy on demand, release deliberately",
        minutes: 31,
        objectives: ["Distinguish deployment from release", "Plan push-button promotion", "Use release strategies to reduce coupling"],
        prerequisites: ["The deployment pipeline", "Automated acceptance testing"],
        concepts: [
          { title: "Two different decisions", paragraphs: ["Deployment installs a specific version into an environment. Release makes functionality available to users. Keeping these decisions separate lets teams rehearse deployment and place inactive changes in production before a business release.", "The pipeline should allow an authorized person to select a passing candidate and deploy it using the same tested mechanism. Approvals control permission; they should not introduce a separate manual procedure."] },
          { title: "Decouple with configuration", paragraphs: ["Feature toggles can hide incomplete or unreleased behavior while changes remain integrated on mainline. Dark launching can exercise technical paths without exposing the feature broadly.", "Toggles add complexity and need ownership and removal plans. They are not a substitute for tests or a reason to leave unsafe code paths indefinitely."] },
        ],
        terms: [["Deployment", "Installing a version into an environment."], ["Release", "Making functionality available to intended users."], ["Feature toggle", "A controlled switch that changes whether functionality is exposed."],
        ],
        method: ["Choose a passing identified candidate.", "Obtain required authorization.", "Deploy with the standard script.", "Smoke-test and monitor the result.", "Expose functionality according to the release plan."],
        example: { title: "A scheduled product announcement", scenario: "Code is ready Monday but marketing launches Thursday.", steps: ["Deploy the passing candidate before Thursday with the feature disabled.", "Verify the inactive path and normal service.", "At launch, change the controlled release setting and monitor."], result: "Technical deployment risk is separated from the time-sensitive business release." },
        mistakes: ["Using 'deploy' and 'release' as if they are always the same event", "Adding approval by replacing automation with manual commands", "Leaving old feature toggles forever"],
        check: { question: "Which action is a release rather than a deployment?", answers: ["Copying version 12 to production", "Enabling a deployed feature for customers", "Building an artifact", "Running unit tests"], correct: 1, explanation: "Release changes user availability; deployment changes what version is installed." },
        practice: { prompt: "Plan a Thursday release for code ready on Monday.", hint: "Separate installation, verification, and exposure.", answer: "Deploy the verified candidate with controlled functionality disabled, smoke-test and monitor it, then authorize and enable the feature Thursday with a clear rollback or disable path." },
        summary: ["Deployment installs; release exposes.", "Authorized promotion should use the same rehearsed automation.", "Controlled toggles can reduce timing and integration risk."],
      }),
      lesson({
        id: "rollback-zero-downtime",
        title: "Rollback and zero-downtime change",
        minutes: 36,
        objectives: ["Choose roll-forward or rollback", "Plan compatible changes", "Explain zero-downtime deployment principles"],
        prerequisites: ["Deploy on demand, release deliberately"],
        concepts: [
          { title: "Recovery is part of the plan", paragraphs: ["Every production change needs success criteria and a remediation strategy. A rollback restores a known-good application version; a roll-forward applies a corrective change. The right choice depends on speed, data compatibility, and confidence.", "Practice recovery before the incident. Keep prior artifacts available and automate the same path used for normal deployment."] },
          { title: "Change without stopping service", paragraphs: ["Zero-downtime releases require old and new versions to coexist during transition. Use backward-compatible interfaces and data changes, bring up the new version, verify it, shift traffic, then remove the old version.", "Destructive schema changes cannot safely precede code that still depends on the old shape. Expand first, migrate use, then contract in a later release."] },
        ],
        terms: [["Rollback", "Restore a previously known-good application version."], ["Roll-forward", "Repair production by deploying a new corrective version."], ["Backward compatible", "A change that still supports clients or versions using the previous contract."],
        ],
        method: ["Define health and success criteria.", "Keep a known-good artifact and compatible data path.", "Deploy the new version alongside or incrementally.", "Verify and shift traffic.", "Rollback or roll forward when criteria fail."],
        example: { title: "Renaming a database column", scenario: "Old application instances read customer_name while the new version expects name.", steps: ["Add name without removing customer_name.", "Write data compatibly and migrate existing rows.", "Deploy code that reads the new field with a transition fallback.", "Remove the old field only after no old version depends on it."], result: "Old and new versions can coexist, allowing safe traffic shift and recovery." },
        mistakes: ["Assuming application rollback reverses data changes", "Making a destructive schema change first", "Keeping no previous artifact because source can be rebuilt"],
        check: { question: "Why use expand-and-contract for data changes?", answers: ["To make migrations slower", "To keep old and new application versions compatible during transition", "To avoid version control", "To skip monitoring"], correct: 1, explanation: "Compatibility allows mixed versions during deployment and preserves recovery options." },
        practice: { prompt: "Plan recovery for a release that changes an API response and stored data.", hint: "Preserve compatibility before shifting traffic.", answer: "Add the new API/data shape while keeping the old contract, migrate safely, deploy and verify the compatible application, shift traffic, and remove the old contract only in a later release. Retain known-good artifacts and explicit health triggers." },
        summary: ["Recovery automation is part of release design.", "Data compatibility determines whether rollback is safe.", "Expand, migrate, and contract across separate releases."],
      }),
    ],
  },
  {
    id: 11,
    title: "Infrastructure and Environments",
    summary: "Create, change, and monitor environments through controlled automation.",
    minutes: 64,
    difficulty: "Intermediate",
    topics: ["infrastructure", "virtualization", "monitoring"],
    lessons: [
      lesson({
        id: "environment-automation",
        title: "Automate environment creation",
        minutes: 31,
        objectives: ["Describe environment configuration management", "Design a reproducible environment", "Explain the role of virtualization"],
        prerequisites: ["Configuration management", "Deployment automation"],
        concepts: [
          { title: "Infrastructure is part of the system", paragraphs: ["Operating systems, network settings, middleware, accounts, and application configuration all affect behavior. Record their desired state and provision them through automation rather than a sequence of remote logins.", "A new environment should be reproducible from controlled definitions. Access to change it should be limited, and routine changes should flow through the same audited mechanism."] },
          { title: "Disposable does not mean unmanaged", paragraphs: ["Virtualization and on-demand infrastructure can make it cheap to create test environments, run work, and discard them. That speed is useful only when images and configuration are identified and repeatable.", "Capture durable definitions and data, not mysterious machines. If an environment drifts, correcting or recreating it from the declared state is safer than preserving undocumented repairs."] },
        ],
        terms: [["Provisioning", "Creating and configuring infrastructure for use."], ["Virtualization", "Running isolated machine environments on shared physical resources."], ["Environment baseline", "The identified operating-system, stack, network, and configuration state."],
        ],
        method: ["Declare the complete environment baseline.", "Provision through versioned automation.", "Apply application configuration and deploy.", "Run infrastructure and application smoke tests.", "Record identity, ownership, and changes."],
        example: { title: "A vanished test server", scenario: "A server fails and nobody knows which manual packages it had.", steps: ["Repair depends on memory because state was never declared.", "Create a versioned baseline and provisioning script.", "Rebuild a replacement and verify it automatically."], result: "Environment loss becomes a routine recreation instead of forensic recovery." },
        mistakes: ["Treating servers as irreplaceable pets", "Versioning application code but not the software stack", "Giving broad manual access instead of a controlled change path"],
        check: { question: "What proves environment reproducibility?", answers: ["A checklist exists", "A new environment can be created from controlled definitions", "The original server is still running", "One administrator remembers it"], correct: 1, explanation: "Recreation from declared assets is stronger evidence than documentation or memory alone." },
        practice: { prompt: "List the minimum controlled inputs for recreating a web environment.", hint: "Cover machine, network, stack, application, and configuration.", answer: "Include OS/image and patches, network rules, accounts/access, runtime and middleware versions, provisioning scripts, application artifact identifier, environment configuration, and verification tests." },
        summary: ["Environment state belongs in configuration management.", "On-demand infrastructure still needs unique, reproducible definitions.", "Recreation is the practical test of control."],
      }),
      lesson({
        id: "environment-monitoring",
        title: "Monitor environments and behavior",
        minutes: 33,
        objectives: ["Separate infrastructure and behavior monitoring", "Create actionable alerts", "Use monitoring as release feedback"],
        prerequisites: ["Automate environment creation"],
        concepts: [
          { title: "Observe the service users receive", paragraphs: ["Infrastructure metrics such as CPU, disk, and memory help diagnose problems, but they do not directly prove that users can complete important work. Behavior-driven monitoring continuously checks critical service outcomes.", "Combine technical signals, application logs, and synthetic business transactions. Attach the deployed artifact and configuration identity so a change can be correlated with a symptom."] },
          { title: "Alerts demand action", paragraphs: ["An alert needs an owner, a meaningful threshold, and a response. Too many unactionable alerts create noise and hide real incidents.", "Deployment should increase attention to health. Compare success criteria, stop a rollout when they fail, and feed incidents back into tests, automation, and capacity planning."] },
        ],
        terms: [["Synthetic transaction", "An automated check that performs a user-like service action."], ["Actionable alert", "A notification with meaningful evidence, ownership, and a defined response."], ["Observability", "Evidence that helps infer internal system state from its outputs."],
        ],
        method: ["Choose critical user outcomes.", "Add synthetic checks and technical signals.", "Tag signals with version and environment.", "Define thresholds, owner, and response.", "Review incidents and improve the delivery system."],
        example: { title: "CPU looks healthy, checkout is broken", scenario: "Servers use 30% CPU, but payments fail because an external endpoint is unreachable.", steps: ["CPU alone misses the user outcome.", "A synthetic checkout detects the failure.", "Dependency and application logs explain the boundary problem.", "The release process can pause or recover."], result: "Behavior plus technical evidence detects and diagnoses what users experience." },
        mistakes: ["Monitoring only machine utilization", "Alerting without ownership", "Failing to connect incidents to the deployed candidate"],
        check: { question: "Which signal most directly tests customer value?", answers: ["Disk temperature", "A successful synthetic checkout", "Number of servers", "Log file size"], correct: 1, explanation: "A synthetic business transaction observes whether a critical user outcome works." },
        practice: { prompt: "Design one actionable release alert for a login service.", hint: "Include outcome, threshold, version context, owner, and action.", answer: "Alert when synthetic login success falls below the agreed threshold for a short window, include version/environment and failure evidence, page the service owner, pause rollout, and follow the documented recovery path." },
        summary: ["Monitor user outcomes as well as infrastructure.", "Tag evidence with the exact deployed state.", "Every alert needs ownership and a response."],
      }),
    ],
  },
  {
    id: 12,
    title: "Managing Data",
    summary: "Evolve schemas and test data without breaking delivery.",
    minutes: 66,
    difficulty: "Intermediate",
    topics: ["migrations", "test data", "backward compatibility"],
    lessons: [
      lesson({
        id: "database-migrations",
        title: "Version and migrate databases",
        minutes: 33,
        objectives: ["Treat schema as versioned code", "Design incremental migrations", "Coordinate application and data compatibility"],
        prerequisites: ["Configuration management", "Rollback and zero-downtime change"],
        concepts: [
          { title: "The database evolves with the application", paragraphs: ["Schema definitions, reference data, and migration scripts are part of the system baseline. Store them in version control and apply them automatically in a known order.", "A migration should record whether it ran and fail safely when assumptions are not met. Test migrations on representative data, including upgrade from the current production state."] },
          { title: "Small compatible steps", paragraphs: ["Coordinate schema and code so adjacent versions can coexist. Add new structures first, migrate data, switch application use, and remove old structures later.", "Large migrations may take time or lock data. Rehearse their duration, failure modes, and recovery; do not assume that rolling back application binaries undoes a data transformation."] },
        ],
        terms: [["Migration", "A versioned change that moves data or schema from one known state to another."], ["Reference data", "Controlled data required for application behavior, such as codes or categories."], ["Schema version", "The identified migration state of a database."],
        ],
        method: ["Create a small forward migration.", "Make it compatible with current and next code where needed.", "Test from a production-like prior state.", "Apply automatically and record completion.", "Verify data and application behavior."],
        example: { title: "Adding a required field", scenario: "A new version needs customer_region, but existing rows have no value.", steps: ["Add the field as optional.", "Deploy code that can populate it while tolerating old rows.", "Backfill and verify existing data.", "Enforce the constraint in a later migration."], result: "The change avoids a single breaking switch and supports safe transition." },
        mistakes: ["Applying production schema changes by hand", "Combining add, backfill, and destructive removal in one step", "Assuming application rollback restores transformed data"],
        check: { question: "Why version migration scripts with application code?", answers: ["To make repositories larger", "To reproduce and trace compatible system states", "To avoid testing data", "To hide production changes"], correct: 1, explanation: "Application and schema versions jointly define a working release and must be traceable." },
        practice: { prompt: "Plan a safe migration from full_name to first_name and last_name.", hint: "Use expand, migrate, switch, and contract.", answer: "Add the new fields, deploy compatible code, backfill and verify names with an explicit rule for ambiguous cases, switch reads/writes, then remove full_name only after all versions and recovery windows no longer require it." },
        summary: ["Schema and data changes are versioned delivery assets.", "Use small compatible migrations across releases.", "Test upgrades and recovery with representative data."],
      }),
      lesson({
        id: "test-data",
        title: "Control test data through the pipeline",
        minutes: 33,
        objectives: ["Choose test-data strategies", "Keep tests isolated and repeatable", "Protect sensitive production information"],
        prerequisites: ["Version and migrate databases", "Automated acceptance testing"],
        concepts: [
          { title: "Data is a test input", paragraphs: ["Tests should create the smallest data needed for their purpose or load a known baseline. Uncontrolled shared databases make results depend on history and test order.", "Different stages need different data: focused tests use small constructed examples; acceptance tests need representative business cases; capacity tests need realistic volume and distribution."] },
          { title: "Production data needs care", paragraphs: ["Production copies may contain sensitive information and accidental side effects such as sending real messages. Prefer generated data; when real structure is necessary, sanitize it rigorously and restrict access.", "Reset, migrate, and verify test databases through automation. The database state should be identifiable just like the application candidate tested against it."] },
        ],
        terms: [["Test-data baseline", "A known starting data set for repeatable tests."], ["Sanitization", "Removing or transforming sensitive data so people cannot be identified or harmed."], ["Data isolation", "Ensuring one test's records do not change another test's outcome."],
        ],
        method: ["Match data shape and volume to the test purpose.", "Generate or load an identified baseline.", "Create unique records per test.", "Disable real external side effects.", "Reset and verify state automatically."],
        example: { title: "Acceptance tests share one account", scenario: "One test locks the account and another then fails to log in.", steps: ["The second result depends on execution order.", "Give each test a unique account or reset controlled state.", "Keep a separate integration check for shared-system behavior if needed."], result: "Tests become independent and safe to run in any order or parallel." },
        mistakes: ["Using an unsanitized production copy", "Letting tests depend on execution order", "Using tiny uniform data for capacity claims"],
        check: { question: "What is safest for routine acceptance tests?", answers: ["An uncontrolled production clone", "Small generated data owned by each test", "One shared account forever", "Whatever data happens to exist"], correct: 1, explanation: "Owned generated data is repeatable, isolated, and avoids exposing production information." },
        practice: { prompt: "Choose data for unit, acceptance, and capacity tests of search.", hint: "Each stage asks a different question.", answer: "Use tiny constructed examples for search rules, representative generated records and edge cases for acceptance, and production-like volume/distribution with sanitized or synthetic content for capacity." },
        summary: ["Match data to the evidence a stage needs.", "Automated baselines and unique records improve repeatability.", "Prefer generated data and protect any production-derived information."],
      }),
    ],
  },
  {
    id: 13,
    title: "Components and Dependencies",
    summary: "Keep large systems releasable while components evolve independently.",
    minutes: 68,
    difficulty: "Advanced",
    topics: ["components", "dependency graphs", "integration pipelines"],
    lessons: [
      lesson({
        id: "releasable-components",
        title: "Keep component changes releasable",
        minutes: 32,
        objectives: ["Define a component boundary", "Keep mainline releasable", "Use incremental change instead of long-lived branches"],
        prerequisites: ["Continuous integration", "Deployment pipeline"],
        concepts: [
          { title: "Integrate incomplete work safely", paragraphs: ["A component is an encapsulated, independently identifiable part of a system. Components can help teams scale, but boundaries and interfaces introduce integration risk.", "Keep work integrated on mainline while hiding incomplete behavior behind safe abstractions or toggles. Make interface changes in compatible steps so producers and consumers do not have to switch at the same instant."] },
          { title: "Prefer releasability over branch inventory", paragraphs: ["Long-lived feature branches postpone the moment when the complete application is tested. Small mainline changes, branch by abstraction, and controlled toggles keep integration evidence current.", "A releasable mainline does not mean exposing every unfinished feature. It means the integrated system can be deployed safely with unfinished behavior inactive."] },
        ],
        terms: [["Component", "An encapsulated, identifiable module with explicit dependencies and interfaces."], ["Branch by abstraction", "Changing an implementation behind a stable abstraction in incremental mainline steps."], ["Releasable mainline", "An integrated state that can be safely released on demand."],
        ],
        method: ["Introduce a stable abstraction.", "Add the new implementation behind it.", "Switch consumers incrementally.", "Verify the integrated application continuously.", "Remove the old implementation and temporary controls."],
        example: { title: "Replacing a pricing service", scenario: "A new implementation will take three weeks.", steps: ["Create an interface around current pricing behavior.", "Build the new implementation behind that interface on mainline.", "Compare or toggle use for controlled cases.", "Remove the old path only after verification."], result: "The system stays integrated and releasable throughout the replacement." },
        mistakes: ["Equating component boundaries with organizational layers", "Keeping a replacement isolated until a final big merge", "Leaving temporary abstractions and toggles indefinitely"],
        check: { question: "What is the main advantage of branch by abstraction?", answers: ["It avoids all tests", "It allows incremental integrated change behind a stable boundary", "It creates a permanent branch", "It removes component interfaces"], correct: 1, explanation: "The abstraction lets old and new implementations coexist while mainline remains releasable." },
        practice: { prompt: "Plan an incremental replacement of a tax calculator.", hint: "Stabilize the boundary, coexist, switch, then clean up.", answer: "Extract a tax interface, keep the old implementation passing existing tests, add the new calculator, compare results on selected cases, switch through controlled configuration, then remove the old path after acceptance." },
        summary: ["Components need explicit boundaries and integration evidence.", "Incremental compatible changes keep mainline releasable.", "Temporary toggles and abstractions require removal plans."],
      }),
      lesson({
        id: "dependency-graphs",
        title: "Version dependencies and integration pipelines",
        minutes: 36,
        objectives: ["Read a dependency graph", "Explain why cycles are harmful", "Design component and integration pipelines"],
        prerequisites: ["Keep component changes releasable", "Artifact management"],
        concepts: [
          { title: "Every dependency has a version", paragraphs: ["A component build must identify the exact versions of libraries and other components it uses. Floating dependencies make failures difficult to reproduce and the last good combination difficult to recover.", "Draw dependencies as a directed graph. A cycle means components depend on one another in a loop, weakening boundaries and making build, test, and release order difficult."] },
          { title: "Test parts and the assembled system", paragraphs: ["Each component has a pipeline that produces a tested artifact. An integration pipeline assembles compatible versions and tests the complete application.", "Run integration often. If many component versions change between runs, diagnosis becomes forensic work. Use enough automation and computing capacity to test likely combinations quickly."] },
        ],
        terms: [["Dependency graph", "A directed map showing which components require others."], ["Directed acyclic graph", "A dependency graph with direction and no circular paths."], ["Integration pipeline", "A pipeline that assembles component versions and tests the complete system."],
        ],
        method: ["Identify every direct dependency and version.", "Draw the directed graph.", "Remove cycles by clarifying ownership or interfaces.", "Build and test each component.", "Assemble identified versions and run integration evidence frequently."],
        example: { title: "A circular build", scenario: "Billing imports Reports, and Reports imports Billing.", steps: ["Neither component has an independent direction of dependency.", "Extract the shared contract or lower-level model into an owned component.", "Make both depend on that contract, not on each other."], result: "The graph becomes acyclic and build/release order is explicit." },
        mistakes: ["Depending on 'latest'", "Testing components but never an assembled application", "Accepting cycles as harmless convenience"],
        check: { question: "Why should a dependency graph be acyclic?", answers: ["To make diagrams prettier", "To keep build and ownership relationships explicit and independently manageable", "To remove versioning", "To prevent all shared code"], correct: 1, explanation: "Cycles tightly couple release and build order and signal unclear component boundaries." },
        practice: { prompt: "A build uses latest-auth and payments-3.2. Improve reproducibility.", hint: "Identify every input and test the combination.", answer: "Replace latest-auth with an exact version, record both versions in the build metadata, retain their artifacts, and run an integration pipeline against that identified combination." },
        summary: ["Pin every component and library dependency.", "Acyclic graphs clarify build and ownership direction.", "Component pipelines and an integration pipeline provide complementary evidence."],
      }),
    ],
  },
  {
    id: 14,
    title: "Version Control and Delivery Governance",
    summary: "Choose integration patterns and govern change with evidence.",
    minutes: 72,
    difficulty: "Advanced",
    topics: ["branching", "risk", "compliance"],
    lessons: [
      lesson({
        id: "version-control-patterns",
        title: "Choose a version-control strategy",
        minutes: 34,
        objectives: ["Compare optimistic and pessimistic locking", "Evaluate branching costs", "Protect a releasable mainline"],
        prerequisites: ["Continuous integration", "Releasable components"],
        concepts: [
          { title: "Integrate text frequently", paragraphs: ["Optimistic version control lets people edit concurrently and resolves overlap during integration. Text merges usually work well when changes are small and frequent. Binary assets may require explicit locking because meaningful merge is not possible.", "Branches isolate change but also delay evidence. The longer a branch lives, the more untested inventory and merge risk it carries. A team is practicing CI only when its work returns to shared mainline frequently."] },
          { title: "Use patterns for a reason", paragraphs: ["Mainline development gives the shortest integration loop. Short-lived branches can support a workflow if they merge at least daily and run tests. Release branches may isolate maintenance of a shipped version, but excessive branching creates a complex release graph.", "Choose the simplest strategy that keeps the application releasable and makes the important integration happen continuously."] },
        ],
        terms: [["Optimistic locking", "Concurrent editing with conflicts resolved when changes are integrated."], ["Merge conflict", "Overlapping edits that require a person to choose the intended result."], ["Release branch", "A line maintained for a released version while mainline continues."],
        ],
        method: ["Identify the integration point that must stay releasable.", "Keep changes small and synchronize frequently.", "Run automated evidence on every branch and merge.", "Merge work to mainline at least daily for CI.", "Retire branches when their purpose ends."],
        example: { title: "A month-long feature branch", scenario: "The branch changes shared pricing code and merges just before release.", steps: ["A month of other mainline changes has not been tested with it.", "Break the feature into compatible hidden increments.", "Integrate those increments daily and keep incomplete behavior disabled."], result: "Integration risk becomes many small feedback events instead of one release crisis." },
        mistakes: ["Calling work continuous integration when branches merge weekly", "Using pessimistic locks for mergeable text by default", "Keeping branches after their purpose is gone"],
        check: { question: "When does a branch still support continuous integration?", answers: ["When it merges to mainline frequently and automated tests run", "When it lives until release", "When nobody else can see it", "When it skips commit tests"], correct: 0, explanation: "The defining behavior is frequent integration with the shared system and immediate feedback." },
        practice: { prompt: "A five-person team has 12 long-lived branches. Propose a transition.", hint: "Reduce branch inventory while preserving unfinished work safely.", answer: "Select a releasable mainline, stop creating long-lived branches, split work into small compatible changes, use abstractions or toggles for incomplete features, test every merge, and retire branches as their changes integrate." },
        summary: ["Frequent small integration makes optimistic merging effective.", "Branches carry delayed-integration cost.", "Choose the simplest strategy that preserves a releasable shared state."],
      }),
      lesson({
        id: "govern-continuous-delivery",
        title: "Govern risk with delivery evidence",
        minutes: 38,
        objectives: ["Connect governance with delivery evidence", "Design an auditable approval", "Choose useful delivery metrics"],
        prerequisites: ["The complete deployment pipeline", "Version-control strategy"],
        concepts: [
          { title: "Govern the process, not manual ceremony", paragraphs: ["Continuous delivery requires collaboration, executive support, and incremental organizational change. Governance should make risk visible while allowing the proven automated path to operate.", "Access control, segregation of duties where required, and approval can be added to the pipeline. The deployment mechanism remains the same one already exercised in test environments; authorization decides who may promote a passing candidate."] },
          { title: "Evidence for every change", paragraphs: ["A change record should identify the candidate, approvals, automated results, environment, success criteria, and remediation strategy. This is stronger than a meeting that approves a change with little technical evidence.", "Measure cycle time, approval queues, failure and recovery, and pipeline health. Review trends and hold retrospectives. Metrics guide improvement; they should not be used to reward local optimization or hide quality problems."] },
        ],
        terms: [["Audit trail", "Recorded connection among a change, approvals, actions, and results."], ["Remediation strategy", "The planned response if a change does not meet success criteria."], ["MTTR", "Mean time to restore service after a failure."],
        ],
        method: ["Identify the candidate and change owner.", "Attach automated evidence and risk assessment.", "Define success criteria and remediation.", "Authorize promotion through controlled access.", "Monitor the outcome and review delivery metrics."],
        example: { title: "An auditable production change", scenario: "Candidate 1842 needs regulated approval.", steps: ["The record links source, artifact, tests, and staging results.", "An authorized approver reviews risk and remediation, then approves in the pipeline.", "The same deployment script promotes 1842.", "Smoke tests and monitoring record whether success criteria hold."], result: "Control is both stronger and faster because evidence and action are traceable." },
        mistakes: ["Adding manual deployment steps in the name of approval", "Measuring output without recovery or quality", "Making delivery one department's responsibility"],
        check: { question: "What is the best place for a required approval?", answers: ["Inside the pipeline before automated promotion", "In an undocumented chat", "After an untracked manual deployment", "Instead of test evidence"], correct: 0, explanation: "Pipeline approval preserves authorization while keeping the deployment mechanism tested and auditable." },
        practice: { prompt: "Design a minimal production change record.", hint: "Connect identity, evidence, decision, outcome, and recovery.", answer: "Record source and artifact identifiers, requested environment, automated stage results, risk/benefit, approver and time, success criteria, remediation plan, deployment result, smoke tests, monitoring outcome, and follow-up." },
        summary: ["Automation and governance reinforce one another through evidence.", "Approvals should authorize the rehearsed pipeline path.", "Cycle time, failures, recovery, and queues guide continuous improvement."],
      }),
    ],
  },
];

export const allLessons = courseModules.flatMap((module) =>
  module.lessons.map((item, lessonIndex) => ({ ...item, module, lessonIndex })),
);

export function findLesson(pathname: string) {
  const slug = pathname.split("?")[0].split("/").filter(Boolean).at(-1);
  return allLessons.find((item) => item.id === slug) ?? allLessons[0];
}
